# Generated by Django 6.0.2 on 2026-05-11 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('monthly_income', models.FloatField()),
                ('employment_type', models.CharField(choices=[('SALARIED', 'Salaried'), ('BUSINESS', 'Business'), ('FREELANCER', 'Freelancer')], max_length=50)),
                ('loan_amount', models.FloatField()),
                ('existing_debt', models.FloatField()),
                ('credit_score', models.IntegerField()),
                ('utility_payment_score', models.FloatField(default=0)),
                ('mobile_usage_score', models.FloatField(default=0)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_tier', models.CharField(blank=True, max_length=50, null=True)),
                ('decision', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('CONDITIONAL', 'Conditional'), ('DECLINE', 'Decline')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
