# Generated by Django 6.0.2 on 2026-05-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
