# Generated by Django 6.0.2 on 2026-05-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_loanapplication_confidence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='explanation',
            field=models.JSONField(default=list),
        ),
    ]
