# Generated by Django 6.0.2 on 2026-05-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='risk_tier',
            field=models.CharField(blank=True, choices=[('LOW_RISK', 'Low Risk'), ('MEDIUM_RISK', 'Medium Risk'), ('HIGH_RISK', 'High Risk'), ('PENDING', 'Pending')], default='PENDING', max_length=50),
        ),
    ]
