# Generated by Django 6.0.2 on 2026-05-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_auditlog_options_alter_loanapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CONDITIONAL', 'Conditional'), ('ON_HOLD', 'On Hold')], default='PENDING', max_length=50),
        ),
    ]
