# Generated by Django 6.0.2 on 2026-05-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='email',
            field=models.EmailField(default='psrisaivarsha@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
