# Generated by Django 6.0.2 on 2026-05-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_loanapplication_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='explanation',
            new_name='explanations',
        ),
    ]
