# Generated by Django 6.0.2 on 2026-05-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_rename_explanation_loanapplication_explanations'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='repayment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REPAID', 'Repaid'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=50),
        ),
    ]
