# Generated by Django 6.0.2 on 2026-05-20 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_loanapplication_repayment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='shap_factors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='applications.loanapplication'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='credit_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='existing_debt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='explanations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['status'], name='application_status_5a1c62_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['risk_tier'], name='application_risk_ti_81629f_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['decision'], name='application_decisio_b80a7d_idx'),
        ),
    ]
